### ISSUE TITLE
Remove JSDoc file comments from generated files

### ISSUE THREAD

**Issue by bmish** [eslint/generator-eslint#109]
I'm not a fan of the [JSDoc comments](https://jsdoc.app/tags-file.html) that we add to the top of all the generated JavaScript files (rule implementation file, test file, etc):

```
/**
 * @fileoverview <%= desc %>
 * @author <%= userName %>
 */
```

Why not?

* The rule description gets repeated in too many places (not DRY), including these comments and in `meta.docs.description`. As a result, the description in the comments is usually out-of-sync with the property. And having to update multiple places makes it more of a hassle to update rule descriptions.
* Over-time, there are often many authors that contributed to a rule, not just the original creator.
* Having a prompt to ask for author name also makes it more tedious to use the rule generator (this is one of many prompts that gets asked).

What do you think? Let me know if anyone actually finds these comments valuable.

**Comment by nzakas** [comment]
I’m the one who implemented this because I like having a summary of what the file is and who created it at the top. I don’t like being dropped right into a file with no context. The author name is helpful not just to know who created it (sometimes I’m shocked to see that it’s me) but also to give people credit for their work.

Removing this means people will need to manually add it back in for core rules, which the generator is also intended to be used for. 

If we decide the generator isn’t to be used for core rules anymore, then I’m fine with removing it (though I’d argue at least the file overview comment should be considered a best practice).

**Comment by bmish** [comment]
Thanks for the explanation, it's helpful to understand how others find value in this JSDoc comment. Since you are in favor of keeping this JSDoc comment, I'm fine to close this.
