### ISSUE TITLE
Unnecessary `category` field in template for plugin-based rules

### ISSUE THREAD

**Issue by brandongregoryscott** [eslint/generator-eslint#131]
Hi there! I'm working on writing up a blog post on how to get started writing an ESLint plugin and I wanted to showcase this tool as a quick getting-started point for new users since I found it super helpful to spin up a project and familiarize myself with the structure.

One thing that I noticed in the rule template is the `category` field:
https://github.com/eslint/generator-eslint/blob/dff57cc1adf47d57d911df079a1665478ca54aee/rule/templates/_rule.js#L17

Based on the information I could find about it (via the JSDoc comment in the TypeScript definitions and the note on the [Developer Guide > Working with Rules](https://eslint.org/docs/latest/developer-guide/working-with-rules) page), this sounds like a field that is optional and only used for core rules, not plugin-based rules. 

Can we update the template to conditionally add that section for core-rules only?

Additionally, I did some digging in the ESLint repo and I couldn't find any rules with `category` filled in - that field seems to only be referenced in some test code ([tests/lib/cli-engine/formatters/html.js](https://github.com/eslint/eslint/blob/main/tests/lib/cli-engine/formatters/html.js#L76) and [tests/lib/cli-engine/formatters/json-with-metadata.js](https://github.com/eslint/eslint/blob/main/tests/lib/cli-engine/formatters/json-with-metadata.js#L26)). 

Is this a field that's still used at all? If not, let's remove it from the template (and the documentation site).

**Comment by bmish** [comment]
Awesome to hear you are writing up a blog post and want to showcase this tool!

`meta.docs.category` is very much an optional field that is not officially used for anything. ESLint core and some plugins have historically used it when generating websites/documentation, but ESLint core stopped using it in recent years:
*  https://github.com/eslint/eslint/pull/14594

I'd be interested to hear from the rest of the ESLint team on whether we want to advertise it at all anymore (in the [official documentation](https://eslint.org/docs/latest/developer-guide/working-with-rules) or in the generator).

I do think it often causes confusion because:
* it's not actually used for anything
* it's used inconsistently
* there are no standard categories (`meta.type` which is standardized is much more useful in this regard)

So we should remove it or at least improve the commented explanation about it to reduce confusion (it's fine if some plugins want to continue to use it for their own purposes).

**Comment by nzakas** [comment]
I’d say let’s remove it. It doesn’t serve a purpose at this point so no need to encourage unused data in the file.

**Comment by brandongregoryscott** [comment]
I can take care of this quick then! Do we want to remove its reference from https://github.com/eslint/eslint/blob/main/docs/src/developer-guide/working-with-rules.md#L73 too, or just this generator repo for now?

**Comment by bmish** [comment]
@brandongregoryscott I recommend opening a PR to remove it from that ESLint documentation page and see if people agree with that (I do).
